apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: plans.upgrade.cattle.io
spec:
  group: upgrade.cattle.io
  names:
    kind: Plan
    listKind: PlanList
    plural: plans
    shortNames:
    - plan
    singular: plan
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
