apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: rke2-master-plan
  namespace: system-upgrade
  labels:
    rke2-upgrade: "true"
spec:
  concurrency: 1
  nodeSelector:
    matchExpressions:
      - { key: node-role.kubernetes.io/control-plane, operator: Exists }
  serviceAccountName: system-upgrade
  cordon: true
  upgrade:
    image: rancher/rke2-upgrade:v1.31.0-rke2r1  # Specify the correct image
  prepare:
    args:
      - prepare
      - server
  drain:
    force: true
  channel: https://update.rke2.io/v1-release/channels/latest
  secrets:
    - name: rke2-server-token  # Ensure this secret exists in the system-upgrade namespace
  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
