apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: rke2-master-plan
  namespace: cattle-system
  labels:
    rke2-upgrade: "true"
spec:
  concurrency: 1
  nodeSelector:
    matchExpressions:
      - { key: node-role.kubernetes.io/control-plane, operator: Exists }
  serviceAccountName: system-upgrade
  cordon: true
  upgrade:
    image: rancher/rke2-upgrade:v1.30.1
  prepare:
    args:
    - prepare
    - server
  drain:
    force: true
  version: v1.30.1+rke2r1
  secrets:
    - name: rke2-server-token
  tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
