apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-upgrade-controller
  namespace: system-upgrade
spec:
  replicas: 1
  selector:
    matchLabels:
      app: system-upgrade-controller
  template:
    metadata:
      labels:
        app: system-upgrade-controller
    spec:
      serviceAccountName: system-upgrade
      containers:
      - name: system-upgrade-controller
        image: rancher/system-upgrade-controller
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: system-upgrade
  namespace: system-upgrade
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system-upgrade
subjects:
- kind: ServiceAccount
  name: system-upgrade
  namespace: system-upgrade
roleRef:
  kind: ClusterRole
  name: system-upgrade
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: system-upgrade-config
  namespace: system-upgrade
data:
  # Add any required configuration data here
